name: CICD

on:
  push:


env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  REPO_DIRECTORY: ${{ secrets.REPO_DIRECTORY }}

permissions:
  checks: write

jobs:
  OnPush:
    if: github.ref_name == 'refs/heads/devl'
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Check if Databricks Repository exists
        run: |
          databricks repos list --output json > repos.json
          jq -r ".[].path" repos.json | grep -q "^${REPO_DIRECTORY}$"
          echo "REPO_EXISTS=$?" >> $GITHUB_ENV

      - name: Push to Databricks Repository
        run: |
          REPO_EXISTS=$(cat $GITHUB_ENV | grep "REPO_EXISTS" | cut -d'=' -f2)
          if [ "$REPO_EXISTS" -ne 0 ]; then
            echo "Databricks Repository doesn't exist. Creating..."
            databricks repos create --path $REPO_DIRECTORY
          fi
          cd $REPO_DIRECTORY
          databricks repos import --path . --overwrite
